name: Build and Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build pthread test programs
      run: make -C pthread_tests checkprogs
    - name: Run pthread test programs
      run: make -C pthread_tests check
